### ISSUE TITLE
don't suggest global installs

### ISSUE THREAD

**Issue by alexkrolick** [zeplin/connected-components-docs#13]
Rather than `npm install -g @zeplin/cli`, it's probably safer to document how to set Zeplin up for an individual project, similar to CI or linting configs, especially for plugins (`@zeplin/cli-connect-react-plugin`) that will be referenced in a local config file.

**Comment by yuqu** [comment]
Documentation is revamped, local installation of packages are also suggested. 

Using the [initializer command](https://github.com/zeplin/connected-components-docs/blob/master/docs/gettingStarted/QUICK_START.md#connecting-the-first-component) will install all packages as local packages if possible.
