### ISSUE TITLE
storybook appends --ci to script

### ISSUE THREAD

**Issue by fritzschoff** [zeplin/connected-components-docs#15]
I tried to implement the storybook plugin for the zeplin cli and he always append a `--ci` to the script.
```
Connecting components to Zeplin components failed.

    Script failed to start: 
    > blockframes@0.0.2 storybook:ui /home/max/code/blockframes
    > npx ng run ui:storybook "--ci"

    Unknown option: '--ci'
    npm ERR! code ELIFECYCLE
    npm ERR! errno 1
    npm ERR! blockframes@0.0.2 storybook:ui: `npx ng run ui:storybook "--ci"`
 ```
there is no --ci mention in my package.json, so I think it comes from the zeplin cli?

**Comment by yuqu** [comment]
Hi @Maxstgt ,

`--ci` option is appended to npm scripts in the below line, it tells storybook to not use prompts and not to open browser when it starts.

https://github.com/zeplin/cli-connect-storybook-plugin/blob/f8cecde5e619831dfb94abc41478149b1d1dd516/src/index.ts#L48

I think problem arises from usage of npx, the plugin does not handle it to separate
Short term solution would be to use `command` field on the configuration but also pass --ci yourself.
```
{
    ...
    command: "npx ng run ui:storybook -- --ci"
    ...
}
```
See if it works. If it does not, could you please share plugin part of your configuration file?

**Comment by fritzschoff** [comment]
I removed the npx from my npm script but the error persists. 
config json looks like this ```
"plugins": [
        {
            "name": "@zeplin/cli-connect-angular-plugin",
            "config": {
                "useFullSnippet": true,
                "useFullDescription": true
            }
        },
        {
            "name": "@zeplin/cli-connect-storybook-plugin",
            "config": {
                "url": "http://localhost:4400",
                "startScript": "storybook:ui"
            }
        }
    ]```

**Comment by yuqu** [comment]
What does `storybook:ui` script correspond to in your package.json?

**Comment by fritzschoff** [comment]
`ng run ui:storybook` ui is library in our NX environment

**Comment by yuqu** [comment]
```
{
    "plugins": [
        {
            "name": "@zeplin/cli-connect-angular-plugin",
            "config": {
                "useFullSnippet": true,
                "useFullDescription": true
            }
        },
        {
            "name": "@zeplin/cli-connect-storybook-plugin",
            "config": {
                "url": "http://localhost:4400",
                "command": "npx ng run ui:storybook"
            }
        }
    ]
}
```

I'm sorry for my late response. Could you try the configuration given above? I've added `command` parameter instead of `startScript` as I mentioned in my first comment.

By the way, I've just take a look into your repository. I think finding out matching stories of the components would not work with your setup for two reasons. First problem is that names of your stories does not correspond to component names (e.g. story kind of slider component is named as 'Bf Slider' while the component is named as slider). The other problem is that we are missing a component name resolver that handles component names with Angular convention (like `x.component.ts` is x) in the plugin. We'll be working on to fix the second problem.

You would need to add manual story definitions into your `.zeplin/component.json` file like below.
```
    {
        "path": "libs/ui/src/lib/slider/slider.component.ts",
        "zeplinNames": [
            "component/slider/archipel_content/movie-slider"
        ],
        "storybook": {
            "kind": "Bf Slider"
        }
    }
```
or
```
    {
        "path": "libs/ui/src/lib/slider/slider.component.ts",
        "zeplinNames": [
            "component/slider/archipel_content/movie-slider"
        ],
        "storybook": {
            "kind": "Bf Slider",
            "stories": ["Bf Slider"]
        }
    }
```

**Comment by fritzschoff** [comment]
EDITED:
```
components.json
   {
            "path": "libs/movie/src/lib/movie/components/card/card.component.ts",
            "zeplinNames": [
                "component/card/archipel_content/movie-card-large",
                "component/card/archipel_content/movie-card-large-hover"
            ],
            "storybook": {
                "kind": "Movie Card",
                "storybook": [
                    "Movie Card"
                ]
            }
        }
```
card.stories.ts
```
export default {
  title: 'Movie Card'
};

export const movieCard = () => ({
  moduleMetadata: { imports: [MovieCardModule, ToolkitModule] },
  name: 'Movie Card',
  component: CardComponent,
  template: `
    <storybook-toolkit>
      <h1 title>Movie Card</h1>
      <movie-card [movie]="movie"></movie-card>
    </storybook-toolkit>
  `,
  props: {
    movie: object('movie', MOVIES[0]),
  }
});
```

Thanks for the help! Maybe you can state that in the docs, that would be awesome! Keep up your good work :)
