### ISSUE TITLE
Can't find or create Zeplin global configuration file or components.json

### ISSUE THREAD

**Issue by deborah-ufw** [zeplin/connected-components-docs#24]
Hi everyone, thank you for this excellent plugin!

I'm finding the documentation for getting Storybook hooked up with Zeplin to be very confusing. Most of the documentation refers to a .zeplin folder - I can not find this folder or file anywhere on my MacOS drive (I've even checked the Zeplin package in Applications). However, it must be somewhere because once the Zeplin extension is installed in VSCode and I've logged in, it allows me to find add my Zeplin projects, and the projects persist even when I uninstall+reinstall the Zeplin VSCode plugin. 

The VSCode plugin did not prompt as promised to create the file, it apparently did it some other way (the command to create it also failed without error), and it is not at the root of my workspace or repository, so I can't find it to make the configuration additions for Storybook.

I've tried to create .zeplin and /components.json manually, but the plugin is not populating this file.

Overall, it seems like the documentation for these awesome features needs review, but for now I can't figure out where to make the Storybook component adjustments. Can anyone tell me where on my drive to find the configuration files? And how the files should be moved to my repo and properly hooked up to the plugin, so my team can have visibility when using Zeplin to begin feature development?

**Comment by deborah-ufw** [comment]
hi everyone, my main problem was that by the time I got to [this document](https://github.com/zeplin/connected-components-docs/blob/master/docs/gettingStarted/ALL.md.) from the in-app Zeplin "Connect to Code" button (which leads to a product page with a "Get Started" button), I had already read repetitive information and missed that installing the main zeplin cli is a pre-requisite. This requirement is in the middle of the page, after installing SB cli and was easy to miss.

Consequently, I never installed the main zeplin cli, so nothing worked. 

Putting this at the top of the process for connecting would help other cases like mine. 

I received great instructions from Josh at Zeplin by email and was able to connect. Thank you Josh!

**Comment by uxbritt** [comment]
I agree, I did not understand there was a prerequisite to install: [npm install -g zeplin/cli ](https://github.com/zeplin/cli)
before installing [npm install -g @zeplin/cli-connect-react-plugin](https://github.com/zeplin/cli-connect-react-plugin)
