### ISSUE TITLE
Components are either 'not found' or 'loading...' depending on the syntax

### ISSUE THREAD

**Issue by marcolabreu** [zeplin/connected-components-docs#27]
I'm not succeeding in loading my components. The Storybook version is 6.0.21. My `main.js` looks like bellow. 
**Obs.** The new Storybook config syntax doesn't seem to require the `/register` anymore, but alas, I've tried with and without it with the exact same results.

```javascript
//main,js
module.exports = {
  stories: ["../src/**/*.stories.mdx", "../src/**/*.stories.@(js|jsx|ts|tsx)"],
  addons: [
    "@storybook/addon-essentials",
    "@storybook/addon-links",
    "@storybook/addon-storysource",
    "@storybook/preset-scss",
    "storybook-addon-designs",
    "storybook-zeplin/register", 
  ],
};
```

Depending on the syntax I get either _Component not found_ or an endless _Loading..._. 

If `zeplinLink` is an array of strings or an object with `name` and `link` like the examples bellow, I get the latter. Checking the Inspector Network tab, there's a line `__webpack_hmr` for which Time keeps growing on Chrome or have a spinner on Safari. Never times out. 

```javascript
// array of strings
SomeStory.story = {
  args: {
    icon: "import_contacts",
    name: "Contacts",
    to: "#",
  },
  parameters: {
    zeplinLink: [
      "https://app.zeplin.io/project/5f2814056bbe442000933c39/styleguide/components?coid=xxxxx",
      "zpl://components?pid=xxxxx&coid=yyyyy",
    ],
  },
};
```

```javascript
// object
AnotherStory.story = {
  args: {
    icon: "contact_phone",
    name: "Extensions",
    to: "#",
  },
  parameters: {
    zeplinLink: {
      name: "Name",
      link:
        "zpl://components?pid=xxxxx&coid=yyyyy",
    },
  },
};
```

Any other syntax variations I've tried result in _Component not found_. 

Authentication seems to be working. If I use a bogus `STORYBOOK_ZEPLIN_TOKEN`, the stories reporting _Component not found_ will complain about the invalid token. The stories stuck on _Loading..._ won't change at all, which seems to imply those syntax shown above are not supported or working.

How can we further debug this?

**Comment by yuqu** [comment]
Hey,

I guess your issue is about this Storybook addon https://github.com/mertkahyaoglu/storybook-zeplin which is unrelated to Connected Components feature of Zeplin. Could you open an issue there?
