### ISSUE TITLE
feat: hide the generated zeplin code

### ISSUE THREAD

**Issue by BaptisteCool** [zeplin/connected-components-docs#30]
Add an option to not show the default code in zeplin

**Comment by yuqu** [comment]
Hey, could you give an example of the proposed feature? Hiding code for individual components, or all of them at once? If what you mean is the latter, you can just remove the related plugin on the configuration file.

**Comment by BaptisteCool** [comment]
Hi, i just tested with the plugin-vue, i will test without.

**Comment by BaptisteCool** [comment]
It's ok without the plugin.
![image](https://user-images.githubusercontent.com/6760432/101644346-5ba2b680-3a35-11eb-9cc1-e8f54cbb0048.png)

Is it possible to change the devault string 'No description or code snipet'. ?
