### ISSUE TITLE
What is the best way to get the Zeplin ID for the component?

### ISSUE THREAD

**Issue by deborah-ufw** [zeplin/connected-components-docs#38]
Our team has an unusual export convention from SB so I'm doing a lot of manual connecting. Only I can't figure out how to find the Zeplin ID - especially since I tried already several times to connect most of them and no longer see the "connect" option on the component in Zeplin. Hint?

Thank you so much guys, this is a great tool!

**Comment by yuqu** [comment]
Hey @deborah-ufw, 

You can use Zeplin VS Code extension to fill in other components into the configuration file. 

If you could not use VS Code, to do it manually, you can copy app link of the component and paste it to a text editor, `coid` is the component's Zeplin ID.

zpl://components?pid=5ab33a7928b7751764c16aaa1&coid=**532a1715085755449e9c111d**

<img src="https://user-images.githubusercontent.com/7137767/120894612-f9acbd80-c621-11eb-8725-bc8ec2bb5929.png" width="400px" />

Hope it helps, let us know if you have any other questions.

**Comment by deborah-ufw** [comment]
Thank you so much for the quick and very helpful reply! Cheers and have a great weekend! :D
