### ISSUE TITLE
Stencil Integration? 

### ISSUE THREAD

**Issue by jackdriscollukg** [zeplin/connected-components-docs#41]
Hi everyone! My team just started using zeplin and I was wondering if there was support for stencil.js web component libraries. Can't wait to hear from you.

**Comment by yuqu** [comment]
Hi, you may try [StencilJS plugin](https://github.com/fmontes/zeplin-cli-connect-plugin-stenciljs) developed by the community. We don't have step by step instructions as provided for other official frameworks but you may follow the same steps described in [Getting Started with React](https://github.com/zeplin/connected-components-docs/blob/master/docs/gettingStarted/REACT.md) document, just make sure to adjust the steps given specifically for React with the instructions given on StencilJS plugin README file.
